### ISSUE TITLE
Debug terminal

### ISSUE THREAD

**Issue by otDan** [noidexe/godot-version-manager#25]
You can open any godot editor version thru the terminal to have the debug output in that window, cannot do that thru gvm so maybe add a toggle to open it with the terminal?

**Comment by otDan** [comment]
has this stopped being updated?

**Comment by noidexe** [comment]
Not at all, but I work on this 100% for free on my free time. The last two months have been very busy between trade shows, events, wrapping up projects and moving to a different office so I haven't been able to work on it. I hope this weekend I'll finally be able to get back to it and release an update.

**Comment by noidexe** [comment]
Unfortunately there is no easy way to launch a console using OS.execute(), it will hide text based binaries by default

As a workaround you can launch gvm from a console and when you double click on any project it you'll get debug output

You can create a launcher saving something like the following as `gvm-console.cmd`
```
@echo off
cmd /k gvm.exe
```

**Comment by noidexe** [comment]
If anyone finds a way to do this feel free to send me a PR
