### ISSUE TITLE
Minor, unimportant thing: "requires powershell"

### ISSUE THREAD

**Issue by CamiloMM** [noidexe/godot-version-manager#40]
The Readme says Powershell is required for extraction. I think this might confuse beginners for no reason, since every Windows version released in the past decade and a half comes with Powershell.

I mean, Steam is going to drop support for even Win7-Win8.1 in a couple months, so I don't think this supports as far back as WinXP?

Again, this is a minor, unimportant thing, but I guess a lot of novice gamedevs will look at it and google what is powershell when there's no situation where it will not be present in their systems.

**Comment by noidexe** [comment]
Fixed in 2d332e11514627b43afb895a6e92c70ef8225406
