### ISSUE TITLE
Fix theme on godot4 branch

### ISSUE THREAD

**Issue by noidexe** [noidexe/godot-version-manager#45]

**Comment by Kregap** [comment]
I would like to try helping with the project. Could you add some details? Do you mean project visually looks different on this branch and the task is to make it look close to currently released version?

**Comment by noidexe** [comment]
Yes here's the Godot 3 version:

![image](https://github.com/noidexe/godot-version-manager/assets/526829/55295d6e-e53d-4692-9256-92028c640047)

And here's the Godot 4 version:

![image](https://github.com/noidexe/godot-version-manager/assets/526829/e6d70564-7869-4460-b2e6-f95b7e6e1551)

Doesn't necessarily have to look exactly the same, but the news are lacking the light background. Same thing for the installed version list. It negatively impacts readability. 

There's also a PR adding a dark theme that needs to be forward ported, though that dark theme could be improved a bit first

**Comment by Kregap** [comment]
Still work in progress, but those are current results. Please let me know if I'm taking too much liberty with changing the look of some of controls.
![Godot_v4 2 2-stable_win64_7wv5Yb7X5X](https://github.com/noidexe/godot-version-manager/assets/15647621/a7267503-3de7-474d-a92e-606ab33d7c3a)
![Godot_v4 2 2-stable_win64_qpP3l0J1aa](https://github.com/noidexe/godot-version-manager/assets/15647621/34fc68ba-a2af-467b-b2f1-9d1bae237a6d)

**Comment by noidexe** [comment]
Not at all. I think they look great!

**Comment by Kregap** [comment]
You can find my suggested changes in #53.

**Comment by noidexe** [comment]
Fixed by #53
