### ISSUE TITLE
Doesn't show latest mono releases

### ISSUE THREAD

**Issue by TarunYellapu** [noidexe/godot-version-manager#48]
![Screenshot_20240213_225557](https://github.com/noidexe/godot-version-manager/assets/86869295/64a93e47-f56b-4b3f-b1e2-b6024c49c9f0)
It doesn't show latest mono 4.x releases on linux only shows 3.x releases, works as intended if mono is not checked.

OS: Linux
Distro: EndeavourOS
Processor: Intel 10500h
GPU: UHD 620/RTX 3050 mobile
DE: Plasma

**Comment by noidexe** [comment]
Can you try doing shift-click on the refresh button? It will turn red and
show "full refresh" when you hold shift.
It seems the database is incomplete


Lisandro Lorea

**Comment by TarunYellapu** [comment]
Just did a full refresh but it still shows 3.5.3 as latest mono build.
